version: '3.8'

services:
  mysqldb:
    image: mysql:latest  
    env_file:
      - ./.env
    environment: 
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db:/var/lib/mysql

  app:
    image: node:20-alpine
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: ${DB_HOST}
      MYSQL_USER: ${DB_ROOT}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DB: ${DB_NAME}
    tty: true
volumes:
  db:
